set -g mouse on
set -g default-terminal "tmux-256color"
set -g focus-events on # Claude Code asked me to add this
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
set -g history-limit 10000

unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s

set -g status-interval 5
set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"

run ~/.config/tmux/plugins/tmux-cpu/cpu.tmux
