brew "bat"
brew "container"
brew "fzf"
brew "git"
brew "starship"
brew "tmux"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "appcleaner"
cask "codex"
cask "claude-code@latest"
cask "discord"
cask "obsidian"
cask "tower"
cask "windows-app"
cask "zed"
